default_meta_info:
  Page:
    in_menu: true
    site_title: Damien Pollet
    site_slogan: >
      Assistant professor,
      <a href="http://www.univ-lille1.fr">university of Lille 1, France</a><br/>
      <em>object-oriented software (re)engineering &amp; language design</em>
    author: Damien Pollet
    author_url: http://people.untyped.org/damien.pollet
    description: >
      Website of Damien Pollet, Ph.D
    keywords: >
      software engineering,
      programming languages,
      reengineering,
      visualisation,
      virtual machines,
      object-oriented

default_processing_pipeline:
  Page: tags,erb,maruku,blocks

website.lang: en
tag.langbar.show_single_lang: false
tag.langbar.separator: " · "
# common.sitemap.any_lang: true
# common.sitemap.used_kinds: [page, directory]
