default_meta_info:
  Page:
    in_menu: true
    site_title: Damien Pollet
    site_slogan: >
      Assistant professor,
      <a href="http://www.univ-lille1.fr">university of Lille 1, France</a><br/>
      <em>object-oriented software (re)engineering &amp; language design</em>
    author: Damien Pollet
    author_url: http://people.untyped.org/damien.pollet
    description: >
      Website of Damien Pollet, Ph.D
    keywords: >
      software engineering,
      programming languages,
      reengineering,
      visualisation,
      virtual machines,
      object-oriented
    
default_processing_pipeline:
  Page: blocks,erb,tags,kramdown,head,fragments
  

website.lang: en
tag.langbar.show_single_lang: false
tag.langbar.separator: " · "
tag.date.format: "%Y-%m-%d"
# common.sitemap.any_lang: true
# common.sitemap.used_kinds: [page, directory]
tag.includefile.process_output: true
tag.includefile.escape_html: false
tag.metainfo.escape_html: false

patterns:
  Copy:
    add: [**/*.pdf]
    add: [**/*.ticker]

sources:
  - ['/', Webgen::Source::FileSystem, 'src']
  - ['/publications/', Webgen::Source::FileSystem, '/Users/damien/Documents/Bib/Publications/', '[0-9][0-9][0-9][0-9]/*']

output: [Webgen::Output::FileSystem, '/Users/damien/Sites/website']
output.do_deletion: true
